### ISSUE TITLE
Create external configuration file

### ISSUE THREAD

**Issue by farinap5** [ojalmeida/GREST#12]
Create a configuration file where GREST will take the parameters as a base to configure the server, such as interface and port. In this way the user can dinamize these vital settings.

This file can be written in `.yaml`, something like this:

```yaml
Project: ProjectName
Version: 1.0

Database: 
  DBMS: mysql
  Address: 127.0.0.1
  Port: 3306
  database: grestdb
  Username: Mardenhh
  Password: UdShJhGfDe

Listener:
  Address: 0.0.0.0
  Port: 8080
```
If the program does not find any config file it needs to be able to create a file with default conf, which the user can edit.
